# Generated by Django 4.2.2 on 2023-06-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("data_criacao", models.DateField()),
                ("acesso", models.EmailField(max_length=254)),
                ("imagem", models.ImageField(upload_to="imagens")),
            ],
        ),
    ]
